sudo: false
language: python
python:
  - 3.7
  - 3.8
  - 3.9
cache:
  pip: true

before_install:
 - pip install poetry
 - pip install flake8
 - pip install coverage

install:
  - poetry install

script:
- poetry run flake8 inqbus
- poetry run coverage run --source=inqbus -m unittest discover -b

after_success:
  - travis_wait 45 bin/createcoverage
  - pip install coveralls
  - coveralls

notifications:
  email:
    - volker.jaenisch@inqbus.de